--
require "core.keymaps"
require "core.options"
require "core.plugins"
require "core.lsp"
require "core.treesitter"
require "core.scheme"
require "core.nvim-tree"
require "core.blank"
require "core.cmp"
require "core.comment"
require "core.gitsigns"
require "core.illuminate"
require "core.lualine"
require "core.project"
require "core.telescope"

