-- Add qrc 
-- update qrc on creating files in ui (.qml files) ui/{components,pages}
-- remove file on qrc on removing files in ui 
-- update qrc on moving files
-- update qrc on addding files
-- validate qrc and working directory (and files)
-- [also for assets] assets/{images,etc}
--
-- Add .gitignore 
--
-- Add .clang-format files
--
-- Add cpp src and header
-- Header add ifdef
-- Add class support
